name: cfc
description: Crowdfield Companion (CFC)
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  google_fonts: ^3.0.1
  get: ^4.6.5
  pin_code_fields: ^7.4.0
  http: ^0.13.5
  firebase_auth: ^4.2.2
  firebase_core: ^2.4.0
  cloud_firestore: ^4.3.0
  walletconnect_dart: ^0.0.11
  url_launcher: ^6.1.7
  web3dart: ^2.5.1
  flutter_advanced_drawer: ^1.3.2
  flutter_svg: ^1.1.6
  loading_indicator: ^3.1.0
  device_info_plus: ^8.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.7
  syncfusion_flutter_sliders: ^20.4.42
  flutter_inset_box_shadow: ^1.0.8
  flutter_rating_bar: ^4.0.1
  syncfusion_flutter_pdfviewer: ^20.4.43
  flutter_secure_storage: ^5.0.2
  walletconnect_secure_storage: ^1.0.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  image_path: "assets/images/app_logo.png"
  image_path_android: "assets/images/app_logo.png"
  image_path_ios: "assets/images/app_logo.png"

flutter_native_splash:
  image: "assets/images/app_logo_white.png"
  background_image: "assets/images/cfc_bg_green.jpg"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
